version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - ./sql/init.sql:/init.sql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT 1", "-C"]
      interval: 10s
      retries: 10
      start_period: 30s

  init-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./sql/init.sql:/init.sql
    entrypoint: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P YourStrong!Passw0rd -i /init.sql -C
      "

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony
    ports:
      - "8080:80"
    volumes:
            - .:/var/www/html
            - ./var/sessions:/tmp/sessions
    depends_on:
      - sqlserver
